TEST_COUNTY = "TEST"
TEST_COUNTY2 = "WAKE"
INVALID_COUNTY = "INVALID"
TEST_PARCEL_ID = "0023821"
INVALID_PARCEL_ID = "INVALID"
EMPTY_TEST_COUNTY = "EMPTY"
SOME_COUNTIES = {"WAKE", "JOHNSTON", "DURHAM"}
TEST_REGEX = r"(\d+)"
