COUNTY_PROCESSING_ORDER:
  - 0 # Using these 3 entries as a way to test the error handling in the code
  - COUNTY: 0
  - COUNTY: "EMPTY"

  - COUNTY: "JOHNSTON"
    ORDER:
      - STEP: "SCRAPE"
        METHOD: "GIS_API"
        URL: "https://services8.arcgis.com/c7zH8GcUwDgKkh1u/arcgis/rest/services/WB_BoundariesandGen_gdb/FeatureServer/2/query"
      - STEP: "SCRAPE"
        METHOD: "PLAYWRIGHT"
        ACTIONS:
          - FIND_BY_ID: "submitDisclaimerAccept"
          - CLICK: null
          - FIND_BY_ID: "field_BookPageID_DOT_Volume"
          - ENTER_TEXT: "[DEED_BOOK]"
          - FIND_BY_ID: "searchButton"
          - CLICK: null
      - STEP: "EXTRACT"
        METHOD: "REGEX"
        FIELD: "DEED_BOOK"
        REGEX: 'Deed Book/Page\\s*(\\d+)/(\\d+)'
        SOURCE: "DEED_SOURCE"
      - STEP: "SCRAPE"
        METHOD: "PLAYWRIGHT"
        ACTIONS:
          - FIND_BY_ID: "field_BookPageID_DOT_Page"
          - ENTER_TEXT: "[DEED_PAGE]"
          - FIND_BY_ID: "searchButton"
          - CLICK: null
      - STEP: "EXTRACT"
        METHOD: "REGEX"
        FIELD: "DEED_PAGE"
        REGEX: 'Deed Book/Page\\s*\\d+/(\\d{3,4})'
        SOURCE: "DEED_SOURCE"

    FIELD_MAPPING:
      LAND_AREA: "GISACRES"
      PARCEL_ID: "PARNO"
      OWNER_NAME: "OWNNAME"
      OWNER_NAME2: "OWNNAME2"
      OWNER_MAILING_ADDRESS1: "MAILADD"
      DEED_SOURCE: "SOURCEREF"
      SALE_DATE: "SALEDATE"
      ACRES: "GISACRES"
      BLDG_VALUE: "IMPROVVAL"
      LAND_VALUE: "LANDVAL"
      TOTAL_PROPERTY_VALUE: "PARVAL"
      LEGAL_DESCRIPTION: "LEGDECFULL"
      FULL_STREET_NAME: "SITEADD"
      CITY: "SCITY"
      SUBDIVISION: "SUBDIVISIO"
      ZIP_CODE: "SZIP"

  - COUNTY: "WAKE"
    ORDER:
      - STEP: "SCRAPE"
        METHOD: "GIS_API"
        URL: "https://services1.arcgis.com/nry3yyvaEfskMEXA/arcgis/rest/services/Wake_County_data/FeatureServer/9/query"
        PARAMETERS:
          PARCEL_ID: "[PARCEL_ID]"
      - STEP: "SCRAPE"
        METHOD: "DIRECT"
        FIELD: "PROPERTY_APPRAISER"
        URL: "https://services.wake.gov/realestate/Account.asp?id=[PARCEL_ID]"
      - STEP: "SCRAPE"
        METHOD: "DIRECT"
        FIELD: "GIS"
        URL: "https://maps.raleighnc.gov/imaps/?pin=[PARCEL_ID_ALT]"
      - STEP: "SCRAPE"
        METHOD: "PLAYWRIGHT"
        FIELD: "DEED"
        URL: "https://rodcrpi.wakegov.com/Booksweb/GenExtSearch.aspx"
        ACTIONS:
          - FIND_BY_ID: "ctl00_ContentPlaceHolder1_RadTextBook"
          - ENTER_TEXT: "[DEED_BOOK]"
          - FIND_BY_ID: "ctl00_ContentPlaceHolder1_RadTextPage"
          - ENTER_TEXT: "[DEED_PAGE]"
          - FIND_BY_ID: "ContentPlaceHolder1_btnExtSearch"
          - CLICK:
          - FIND_BY_ID: "ctl00_ContentPlaceHolder1_RadGridResults_ctl00_ctl04_gbcDocument"
          - CLICK:
          - WAIT_FOR_NEW_WINDOW:
          - SWITCH_WINDOW:
          - RETURN: "WINDOW_URL"
      - STEP: "EXTRACT"
        METHOD: "REGEX"
        FIELD: "PLAT_BOOK"
        REGEX: "BM(\\d+)"
        SOURCE: "LEGAL_DESCRIPTION"
      - STEP: "EXTRACT"
        METHOD: "REGEX"
        FIELD: "PLAT_PAGE"
        REGEX: "-\\s*(\\d+)"
        SOURCE: "LEGAL_DESCRIPTION"
        ACTIONS:
          - FIND_BY_ID: "field_PlatPage"
          - ENTER_TEXT: "[PLAT_PAGE]"
          - FIND_BY_ID: "searchButton"
          - CLICK: null
      - STEP: "SCRAPE"
        METHOD: "PLAYWRIGHT"
        FIELD: "PLAT"
        URL: "https://rodcrpi.wakegov.com/Booksweb/GenExtSearch.aspx"
        ACTIONS:
          - FIND_BY_ID: "ctl00_ContentPlaceHolder1_RadTextBook"
          - ENTER_TEXT: "BM[PLAT_BOOK]"
          - FIND_BY_ID: "ctl00_ContentPlaceHolder1_RadTextPage"
          - ENTER_TEXT: "[PLAT_PAGE]"
          - FIND_BY_ID: "ContentPlaceHolder1_btnExtSearch"
          - CLICK:
          - FIND_BY_ID: "ctl00_ContentPlaceHolder1_RadGridResults_ctl00_ctl04_gbcDocument"
          - CLICK:
          - WAIT_FOR_NEW_WINDOW:
          - SWITCH_WINDOW:
          - RETURN: "WINDOW_URL"

    FIELD_MAPPING:
      LAND_AREA: "CALC_AREA"
      PARCEL_ID: "REID"
      PARCEL_ID_ALT: "PIN_NUM"
      OWNER_NAME: "OWNER"
      OWNER_MAILING_ADDRESS1: "ADDR1"
      OWNER_MAILING_ADDRESS2: "ADDR2"
      OWNER_MAILING_ADDRESS3: "ADDR3"
      DEED_BOOK: "DEED_BOOK"
      DEED_PAGE: "DEED_PAGE"
      DEED_DATE: "DEED_DATE"
      ACRES: "DEED_ACRES"
      BLDG_VALUE: "BLDG_VAL"
      LAND_VALUE: "LAND_VAL"
      TOTAL_PROPERTY_VALUE: "TOTAL_VALUE_ASSD"
      LEGAL_DESCRIPTION: "PROPDESC"
      STREET_NAME: "STNAME"
      STREET_TYPE: "STYPE"
      STREET_PREFIX: "STPRE"
      STREET_SUFFIX: "STSUF"
      STREET_NUMBER: "STNUM"
      STREET_MISC: "STMISC"
      SITUS_ADDRESS: "SITE_ADDRESS"
      FULL_STREET_NAME: "FULL_STREET_NAME"
      CITY: "CITY_DECODE"
      PLANNING_JURISDICTION: "PLANNING_JURISDICTION"
      TOWNSHIP: "TOWNSHIP_DECODE"
      YEAR_BUILT: "YEAR_BUILT"
      TOTAL_SALE_PRICE: "TOTSALPRICE"
      SALE_DATE: "SALE_DATE"
      PROPERTY_CLASSIFICATION: "LAND_CLASS_DECODE"
      NUM_STRUCTURES: "TOTSTRUCTS"
      NUM_UNITS: "TOTUNITS"
      OLD_PARCEL_NUMBER: "OLD_PARCEL_NUMBER"
      ZIP_CODE: "ZIPNUM"

  - COUNTY: "DURHAM"
    ORDER:
      - STEP: "SCRAPE"
        METHOD: "DIRECT"
        FIELD: "PROPERTY_APPRAISER"
        URL: "https://taxcama.dconc.gov/camapwa/PropertySummary.aspx?PARCELPK=[PARCEL_PK]"
      - STEP: "SCRAPE"
        METHOD: "DIRECT"
        FIELD: "GIS"
        URL: "https://maps.durhamnc.gov/?pid=[PARCEL_ID]"
      - STEP: "SCRAPE"
        METHOD: "GIS_API"
        URL: "https://services2.arcgis.com/G5vR3cOjh6g2Ed8E/arcgis/rest/services/Parcels_NEW/FeatureServer/0/query"
        PARAMETERS:
          PARCEL_ID: "[PARCEL_ID]"
      - STEP: "SCRAPE"
        METHOD: "PLAYWRIGHT"
        FIELD: "DEED_SOURCE"
        URL: "https://rodweb.dconc.gov/web/search/DOCSEARCH5S1"
        ACTIONS:
          - FIND_BY_ID: "submitDisclaimerAccept"
          - CLICK:
          - FIND_BY_ID: "field_BookPageID_DOT_Volume"
          - ENTER_TEXT: "[DEED_BOOK]"
          - FIND_BY_ID: "field_BookPageID_DOT_Page"
          - ENTER_TEXT: "[DEED_PAGE]"
          - FIND_BY_ID: "searchButton"
          - CLICK:
          - FIND_BY_CLASS: "selfServiceSearchResultList"
          - CLICK:
          - FIND_BY_CLASS: "selfServiceSearchResultNavigation"
          - CLICK:
          - RETURN: "WINDOW_URL"
      - STEP: "SCRAPE"
        METHOD: "PLAYWRIGHT"
        FIELD: "PLAT_SOURCE"
        URL: "https://rodweb.dconc.gov/web/search/DOCSEARCH5S1"
        ACTIONS:
          - FIND_BY_ID: "submitDisclaimerAccept"
          - CLICK:
          - FIND_BY_ID: "field_BookPageID_DOT_Volume"
          - ENTER_TEXT: "[PLAT_BOOK]"
          - FIND_BY_ID: "field_BookPageID_DOT_Page"
          - ENTER_TEXT: "[PLAT_PAGE]"
          - FIND_BY_ID: "searchButton"
          - CLICK:
          - FIND_BY_CLASS: "selfServiceSearchResultList"
          - CLICK:
          - FIND_BY_CLASS: "selfServiceSearchResultNavigation"
          - CLICK:
          - RETURN: "WINDOW_URL"
      - STEP: "EXTRACT"
        METHOD: "REGEX"
        FIELD: "DEED_BOOK"
        REGEX: "Deed Book/Page\\s*(\\d+)/(\\d+)"
        SOURCE: "DEED_SOURCE"
      - STEP: "EXTRACT"
        METHOD: "REGEX"
        FIELD: "DEED_PAGE"
        REGEX: "Deed Book/Page\\s*\\d+/(\\d{3,4})"
        SOURCE: "DEED_SOURCE"
      - STEP: "EXTRACT"
        METHOD: "REGEX"
        FIELD: "PLAT_BOOK"
        REGEX: "(\\d{4})\\s*/\\s*\\d{4}"
        SOURCE: "PLAT_SOURCE"
      - STEP: "EXTRACT"
        METHOD: "REGEX"
        FIELD: "PLAT_PAGE"
        REGEX: "\\d{4}\\s*/\\s*(\\d{4})"
        SOURCE: "PLAT_SOURCE"

    FIELD_MAPPING:
      LAND_AREA: "CALCULATED_ACRES"
      PARCEL_ID: "REID"
      PARCEL_ID_ALT: "PIN"
      PARCEL_PK: "PARCEL_PK"
      OWNER_NAME: "PROPERTY_OWNER"
      OWNER_MAILING_ADDRESS1: "OWNER_MAIL_1"
      SALE_DATE: "DEED_DATE"
      ACRES: "CALCULATED_ACRES"
      DEED_BOOK: "DEED_BOOK"
      DEED_PAGE: "DEED_PAGE"
      DEED_DATE: "DEED_DATE"
      BLDG_VALUE: "TOTAL_BLDG_VALUE_ASSESSED"
      LAND_VALUE: "TOTAL_LAND_VALUE_ASSESSED"
      TOTAL_PROPERTY_VALUE: "TOTAL_PROP_VALUE"
      LEGAL_DESCRIPTION: "PROPERTY_DESCR"
      FULL_STREET_NAME: "LOCATION_ADDR"
      CITY: "CITY"
      ZIP_CODE: "PHYADDR_ZIP"
      ZONING: "ZONING"
      TOWNSHIP: "TOWNSHIP"
      PLAT_BOOK: "PLAT_BOOK"
      PLAT_PAGE: "PLAT_PAGE"

  - COUNTY: "TEST"
    ORDER:
      - STEP: "SCRAPE"
        METHOD: "GIS_API"
        URL: "https://localhost"
        PARAMETERS:
          PARCEL_ID: "[PARCEL_ID]"
      - STEP: "SCRAPE"
        METHOD: "PLAYWRIGHT"
        ACTIONS:
          - FIND_BY_ID: "testButton"
          - CLICK: null
      - STEP: "EXTRACT"
        METHOD: "REGEX"
        FIELD: "TEST_FIELD"
        REGEX: "/w+"
        SOURCE: "TEST_SOURCE"

    FIELD_MAPPING:
      PARCEL_ID: "REID"

  - COUNTY: "INVALID"
    ORDER:
      - STEP: "SCRAPE"
        METHOD: "INVALID_METHOD"
        URL: "https://localhost"
        PARAMETERS:
          PARCEL_ID: "[PARCEL_ID]"
      - STEP: "SCRAPE"
        METHOD: "PLAYWRIGHT"
        ACTIONS:
          - FIND_BY_ID: "[INVALID_ID]"
          - CLICK: null
      - STEP: "EXTRACT"
        METHOD: "REGEX"
        FIELD: "TEST_FIELD"
        REGEX: "(.*)"
        SOURCE: "TEST_SOURCE"

    FIELD_MAPPING:
      PARCEL_ID: "REID"
      INVALID_ID: ""
