COUNTY_URLS:
  JOHNSTON: "https://services8.arcgis.com/c7zH8GcUwDgKkh1u/arcgis/rest/services/WB_BoundariesandGen_gdb/FeatureServer/2/query"
  WAKE: "https://services.arcgis.com/v400IkDOw1ad7Yad/arcgis/rest/services/Raleigh_Parcels_Nash_Square/FeatureServer/0/query"
  TEST: "https://localhost"

COUNTIES_REQUIRING_ADDITIONAL_PROCESSING:
  JOHNSTON:
    DEED_BOOK:
      # Example formatting of DEED_SOURCE: Deed Book/Page 05377/0368
      REGEX: "Deed Book/Page\\s*(\\d+)/(\\d+)"
      SOURCE: "DEED_SOURCE"
    DEED_PAGE:
      REGEX: "Deed Book/Page\\s*\\d+/(\\d{3,4})"
      SOURCE: "DEED_SOURCE"
  WAKE:
    PLAT_BOOK:
      REGEX: "BM(\\d+)"
      SOURCE: "LEGAL_DESCRIPTION"
    PLAT_PAGE:
      REGEX: "-\\s*(\\d+)"
      SOURCE: "LEGAL_DESCRIPTION"

COUNTY_URL_MAPPING:
  JOHNSTON:
    PROPERTY_APPRAISER:
      TYPE: "PLAYWRIGHT"
      TEMPLATE: "https://erec.johnstonnc.com/recorder/web/login.jsp"
      ACTIONS:
        - FIND_INPUT_BY_TEXT: "Public Login"
        - CLICK:
        - SWITCH_WINDOW:
        - WAIT_FOR_ID: "BookPageIDBook"
        - FIND_BY_ID: "BookPageIDBook"
        - ENTER_TEXT: "[DEED_BOOK]"
        - FIND_BY_ID: "BookPageIDPage"
        - ENTER_TEXT: "[DEED_PAGE]"
        - FIND_INPUT_BY_TEXT: "Search"
        - CLICK:
        - SWITCH_WINDOW:
        - WAIT_FOR_ID: "searchResultsTable"
        - FIND_BY_TEXT: "View Image"
        - CLICK:
        - SWITCH_WINDOW:
        - RETURN: "WINDOW_URL"
  WAKE:
    PROPERTY_APPRAISER:
      TYPE: "DIRECT"
      TEMPLATE: "https://services.wake.gov/realestate/Account.asp?id=[PARCEL_ID]"
    DEED:
      TYPE: "PLAYWRIGHT"
      TEMPLATE: "https://rodcrpi.wakegov.com/Booksweb/GenExtSearch.aspx"
      ACTIONS:
        - WAIT_FOR_ID: "ctl00_ContentPlaceHolder1_RadTextBook"
        - FIND_BY_ID: "ctl00_ContentPlaceHolder1_RadTextBook"
        - ENTER_TEXT: "[DEED_BOOK]"
        - FIND_BY_ID: "ctl00_ContentPlaceHolder1_RadTextPage"
        - ENTER_TEXT: "[DEED_PAGE]"
        - FIND_BY_ID: "ContentPlaceHolder1_btnExtSearch"
        - CLICK:
        - WAIT_FOR_ID: "ctl00_ContentPlaceHolder1_RadGridResults_ctl00"
        - FIND_BY_ID: "ctl00_ContentPlaceHolder1_RadGridResults_ctl00_ctl04_gbcDocument"
        - CLICK:
        - WAIT_FOR_NEW_WINDOW:
        - SWITCH_WINDOW:
        - RETURN: "WINDOW_URL"
    PLAT:
      TYPE: "PLAYWRIGHT"
      TEMPLATE: "https://rodcrpi.wakegov.com/Booksweb/GenExtSearch.aspx"
      ACTIONS:
        - WAIT_FOR_ID: "ctl00_ContentPlaceHolder1_RadTextBook"
        - FIND_BY_ID: "ctl00_ContentPlaceHolder1_RadTextBook"
        - ENTER_TEXT: "BM[PLAT_BOOK]"
        - FIND_BY_ID: "ctl00_ContentPlaceHolder1_RadTextPage"
        - ENTER_TEXT: "[PLAT_PAGE]"
        - FIND_BY_ID: "ContentPlaceHolder1_btnExtSearch"
        - CLICK:
        - WAIT_FOR_ID: "ctl00_ContentPlaceHolder1_RadGridResults_ctl00"
        - FIND_BY_ID: "ctl00_ContentPlaceHolder1_RadGridResults_ctl00_ctl04_gbcDocument"
        - CLICK:
        - WAIT_FOR_NEW_WINDOW:
        - SWITCH_WINDOW:
        - RETURN: "WINDOW_URL"
  TEST:
    TEST_APPRAISER:
      TYPE: "SCRAPE"
      TEMPLATE: "https://www.bttaxpayerportal.com/itspublicjo"
      LINK_SELECTOR: "a"
    TEST_APPRAISER_INVALID:
      TYPE: "SCRAPE"
      TEMPLATE: "https://www.bttaxpayerportal.com/itspublicjo"
      LINK_SELECTOR: "#testtest"
    TEST_APPRAISER_INVALID_SELECTOR:
      TYPE: "SCRAPE"
      TEMPLATE: "https://www.bttaxpayerportal.com/itspublicjo"
      LINK_SELECTOR: ""
    TEST_APPRAISER_INVALID_URL:
      TYPE: "SCRAPE"
      TEMPLATE: "https://www.bttaxpayrtal.com/itspublicjo"
      LINK_SELECTOR: "#testtest"
    TEST_INVALID_TYPE:
      TYPE: "INVALID"
      TEMPLATE: "https://www.bttaxpayerportal.com/itspublicjo"
      LINK_SELECTOR: ""

COUNTY_FIELD_MAPPING:
  JOHNSTON:
    LAND_AREA: "GISACRES"
    PARCEL_ID: "PARNO"
    OWNER_NAME: "OWNNAME"
    OWNER_NAME2: "OWNNAME2"
    OWNER_MAILING_ADDRESS1: "MAILADD"
    DEED_SOURCE: "SOURCEREF"
    SALE_DATE: "SALEDATE"
    ACRES: "GISACRES"
    BLDG_VALUE: "IMPROVVAL"
    LAND_VALUE: "LANDVAL"
    TOTAL_PROPERTY_VALUE: "PARVAL"
    LEGAL_DESCRIPTION: "LEGDECFULL"
    FULL_STREET_NAME: "SITEADD"
    CITY: "SCITY"
    SUBDIVISION: "SUBDIVISIO"
    ZIP_CODE: "SZIP"
  WAKE:
    LAND_AREA: "CALC_AREA"
    PARCEL_ID: "REID"
    OWNER_NAME: "OWNER"
    OWNER_MAILING_ADDRESS1: "ADDR1"
    OWNER_MAILING_ADDRESS2: "ADDR2"
    OWNER_MAILING_ADDRESS3: "ADDR3"
    DEED_BOOK: "DEED_BOOK"
    DEED_PAGE: "DEED_PAGE"
    DEED_DATE: "DEED_DATE"
    ACRES: "DEED_ACRES"
    BLDG_VALUE: "BLDG_VAL"
    LAND_VALUE: "LAND_VAL"
    TOTAL_PROPERTY_VALUE: "TOTAL_VALUE_ASSD"
    LEGAL_DESCRIPTION: "PROPDESC"
    STREET_NAME: "STNAME"
    STREET_TYPE: "STYPE"
    STREET_PREFIX: "STPRE"
    STREET_SUFFIX: "STSUF"
    STREET_NUMBER: "STNUM"
    STREET_MISC: "STMISC"
    SITUS_ADDRESS: "SITE_ADDRESS"
    FULL_STREET_NAME: "FULL_STREET_NAME"
    CITY: "CITY_DECODE"
    PLANNING_JURISDICTION: "PLANNING_JURISDICTION"
    TOWNSHIP: "TOWNSHIP"
    YEAR_BUILT: "YEAR_BUILT"
    TOTAL_SALE_PRICE: "TOTSALPRICE"
    SALE_DATE: "SALE_DATE"
    PROPERTY_CLASSIFICATION: "LAND_CLASS_DECODE"
    NUM_STRUCTURES: "TOTSTRUCTS"
    NUM_UNITS: "TOTUNITS"
    OLD_PARCEL_NUMBER: "OLD_PARCEL_NUMBER"
    ZIP_CODE: "ZIPNUM"
  TEST:
    PARCEL_ID: "REID"
