county_urls:
  Raleigh: "https://services.arcgis.com/v400IkDOw1ad7Yad/arcgis/rest/services/Raleigh_Parcels_Nash_Square/FeatureServer/0/query"

county_requires_additional_processing:
  Raleigh: false

field_mappings:
  Raleigh:
    LAND_AREA: "CALC_AREA"
    PARCEL_ID: "REID"
    OWNER_NAME: "OWNER"
    OWNER_MAILING_ADDRESS1: "ADDR1"
    OWNER_MAILING_ADDRESS2: "ADDR2"
    OWNER_MAILING_ADDRESS3: "ADDR3"
    DEED_BOOK: "DEED_BOOK"
    DEED_PAGE: "DEED_PAGE"
    DEED_DATE: "DEED_DATE"
    DEED_ACRES: "DEED_ACRES"
    BLDG_VALUE: "BLDG_VAL"
    LAND_VALUE: "LAND_VAL"
    TOTAL_PROPERTY_VALUE: "TOTAL_VALUE_ASSD"
    LEGAL_DESCRIPTION: "PROPDESC"
    STREET_NAME: "STNAME"
    STREET_TYPE: "STYPE"
    STREET_PREFIX: "STPRE"
    STREET_SUFFIX: "STSUF"
    STREET_NUMBER: "STNUM"
    STREET_MISC: "STMISC"
    SITUS_ADDRESS: "SITE_ADDRESS"
    FULL_STREET_NAME: "FULL_STREET_NAME"
    CITY_CODE: "CITY"
    CITY: "CITY_DECODE"
    PLANNING_JURISDICTION: "PLANNING_JURISDICTION"
    TOWNSHIP: "TOWNSHIP"
    YEAR_BUILT: "YEAR_BUILT"
    TOTAL_SALE_PRICE: "TOTSALPRICE"
    SALE_DATE: "SALE_DATE"
    PROPERTY_CLASSIFICATION: "LAND_CLASS_DECODE"
    NUM_STRUCTURES: "TOTSTRUCTS"
    NUM_UNITS: "TOTUNITS"
    OLD_PARCEL_NUMBER: "OLD_PARCEL_NUMBER"
    ZIP_CODE: "ZIPNUM"
